### ISSUE TITLE
<CR> issues on some servers

### ISSUE THREAD

**Issue by etrnal70** [hrsh7th/cmp-nvim-lsp#1]
- On pylsp, pressing enter on selected option didn't autocomplete the parentheses or any function snippets

https://user-images.githubusercontent.com/5826834/129038162-6efe679e-4414-4883-9e9f-1658b049aff1.mp4

 - On dartls, pressing enter inside parentheses trigger the first completion item even if no option is selected, instead of creating a new line
 
https://user-images.githubusercontent.com/5826834/129033748-7f43fc90-b841-419b-9133-fa10f4c90b01.mp4

 
Both are working on compe

**Comment by hrsh7th** [comment]
I didn't understant the problem of pylsp.

But the dartls problem can be fixed by the following config _now_.

```lua
local cmp = require'cmp'
cmp.setup {
  confirmation = {
    mapping = {
      ['<CR>'] = { behavior = cmp.ConfirmBehavior.Replace }
    }
  }
}
```

**Comment by etrnal70** [comment]
I've updated the issue with the pylsp bug. Btw, tested your dartls solution but it still didn't work :/

**Comment by hrsh7th** [comment]
Sorry. My suggested config is not work. it's nvim-cmp's bug. I will fix it.

**Comment by etrnal70** [comment]
Apologize for the late response, looks like theres an updated mapping configuration for cmp. Awesome it's working now ! I guess keep this issue open until pylsp fixed ?

**Comment by etrnal70** [comment]
Closing this since it looks like it pylsp works in compe because of autopairs. And now autopairs already properly support cmp
