### ISSUE TITLE
CSS (cssls) AutoCompletion not working

### ISSUE THREAD

**Issue by nikbrunner** [hrsh7th/cmp-nvim-lsp#14]
Hi there,
first of all thank you for work! I love your plugins, but recently I ran into a problem.
The completion in `.css` or `.scss` files stopped working. The linting works, but the completion does not.
In comparison everything works fine with `.ts` files. Linting and completion.

I spent some hours now trying to figure out whats wrong, but to no success. 

I should provide some context.
Also, I am not totally new to NeoVim configuration, but far from an expert. 

## What  I tried without success
- Updating NeoVim (Currently I am at `0.6`)
- Looked for similiar issues from other people
- Removed and ReSynced Packer packages
- Various re-ordering and refactoring of code lines related to this issue 

## Context
- For the example here I used a `scss` file, but the same problem remains with `css` files
- For LSP installation I use [lsp-installer](https://github.com/williamboman/nvim-lsp-installer)

<details>
<summary>Config</summary>

- [Packer Config](https://github.com/nikbrunner/nibru.nvim/blob/main/lua/plugins.lua)
- [Cmp Config](https://github.com/nikbrunner/nibru.nvim/blob/main/lua/plug-config/completion.lua)
- [LSP Config](https://github.com/nikbrunner/nibru.nvim/blob/main/lua/plug-config/lsp_config.lua)
</details>

### Screenshots
<details>
<summary>tsserver</summary>

### `:CmpStatus`
![nvim_tsserver_cmp-status](https://user-images.githubusercontent.com/46924729/139574922-50debe1f-99fc-465f-b69a-2961ad2087a2.png)

### `:LspInfo`
![nvim_tsserver_lspinfo](https://user-images.githubusercontent.com/46924729/139574928-ff39e34e-2cb4-4767-82ec-dbd0390162bd.png)
</details>

<details>
<summary>cssls</summary>

### `:CmpStatus`
![nvim_css_cmpstatus](https://user-images.githubusercontent.com/46924729/139574955-38f7d2e7-bde7-46bb-918d-616af21e70a2.png)

### `:LspInfo`
![nvim_css_lspinfo](https://user-images.githubusercontent.com/46924729/139574960-15d598f4-e16b-4f4b-ad46-144385c7e3e5.png)
</details>

**Comment by steven-jostar** [comment]
me too

**Comment by nikbrunner** [comment]
I still have this problem. I even installed LunarVim and there exists the same problem for `.css` files..

**Comment by hrsh7th** [comment]
Did you setup the below setting?

```
-- The nvim-cmp almost supports LSP's capabilities so You should advertise it to LSP servers..
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities = require('cmp_nvim_lsp').update_capabilities(capabilities)

-- The following example advertise capabilities to `clangd`.
require'lspconfig'.clangd.setup {
  capabilities = capabilities,
}```

**Comment by nikbrunner** [comment]
That is what I have. This also worked before.

```lua
local nvim_lsp = require("lspconfig")

-- TODO Fix cssls completion
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities = require("cmp_nvim_lsp").update_capabilities(capabilities)

local servers = {
  "html",
  "cssls",
  "tsserver"
}

for _, lsp in ipairs(servers) do
  nvim_lsp[lsp].setup {
    capabilities = capabilities,
  }
end
```

**Comment by hrsh7th** [comment]
I can't understand... Hm...

I'm installed the cssls by `npm i -g vscode-langservers-extracted@latest`.

**Comment by nikbrunner** [comment]
I get this error message when I am entering an `.scss` file for example.
But I am not sure if that has anything to do with it.

![image](https://user-images.githubusercontent.com/46924729/146144592-9d699503-2ea0-4970-9d7e-080f5961b019.png)

When I run `:CmpStatus` I get this:
![image](https://user-images.githubusercontent.com/46924729/146144708-814a2e8d-599e-4427-91a6-3691a831eada.png)

I will try your npm command and see if this causes a change

**Comment by nikbrunner** [comment]
When I run the `npm` command the Propblem remains.
The "Client 1 quit with exit code 1 and signal 0" error still  occurs and I only get text-buffer completion.

![image](https://user-images.githubusercontent.com/46924729/146145151-6aba8b7e-3373-48ff-a4b6-f88feae1e73e.png)

**Comment by JensPauwels** [comment]
I'm experiencing the same as described by @nikbrunner

**Comment by JensPauwels** [comment]
I just noticed an error in `~/.cache/nvim/lsp.log`. This means that your plugin is probably working fine and it's due to the language server error

[ERROR][2021-12-15 09:14:31] .../vim/lsp/rpc.lua:417    "rpc"   "vscode-css-language-server"    "stderr"        "/usr/local/lib/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/linkedMap.js:40\n        return this._head?.value;\n                          ^\n\nSyntaxError: Unexpected token '.'\n    at wrapSafe (internal/modules/cjs/loader.js:915:16)\n    at Module._compile (internal/modules/cjs/loader.js:963:27)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)\n    at Module.load (internal/modules/cjs/loader.js:863:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:708:14)\n    at Module.require (internal/modules/cjs/loader.js:887:19)\n    at require (internal/modules/cjs/helpers.js:74:18)\n    at Object.<anonymous> (/usr/local/lib/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/api.js:37:21)\n    at Module._compile (internal/modules/cjs/loader.js:999:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)\n"

**Comment by nikbrunner** [comment]
I have the same error in my `~/.cache/nvim/lsp.log`:
```
[ERROR][2021-12-04 16:22:48] .../vim/lsp/rpc.lua:417	"rpc"	"/Users/nibru/.local/share/nvim/lsp_servers/cssls/node_modules/.bin/vscode-css-language-server"	"stderr"	"/Users/nibru/.local/share/nvim/lsp_servers/cssls/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/linkedMap.js:40\n        return this._head?.value;\n                          ^\n\nSyntaxError: Unexpected token '.'\n    at Module._compile (internal/modules/cjs/loader.js:892:18)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)\n    at Module.load (internal/modules/cjs/loader.js:812:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:724:14)\n    at Module.require (internal/modules/cjs/loader.js:849:19)\n    at require (internal/modules/cjs/helpers.js:74:18)\n    at Object.<anonymous> (/Users/nibru/.local/share/nvim/lsp_servers/cssls/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/api.js:37:21)\n    at Module._compile (internal/modules/cjs/loader.js:956:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)\n    at Module.load (internal/modules/cjs/loader.js:812:32)\n"
```

**Comment by JensPauwels** [comment]
Is there any news on this issue?

**Comment by hrsh7th** [comment]
I can't reproduce.

https://user-images.githubusercontent.com/629908/147454160-a8ba7e66-ccb1-4091-a5aa-b97003292f9a.mp4

**Comment by hrsh7th** [comment]
```
hrsh7th$ npm ls -g vscode-langservers-extracted
/Users/hiroshi_shichita/.config/nvm/versions/node/v16.13.0/lib
└── vscode-langservers-extracted@3.0.2
```

**Comment by hrsh7th** [comment]
```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/vim-vsnip'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = {
    { name = "nvim_lsp" },
  },
}

local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities = require("cmp_nvim_lsp").update_capabilities(capabilities)
local lspconfig = require('lspconfig')
lspconfig.cssls.setup {
  capabilities = capabilities
}
EOF
```

**Comment by JensPauwels** [comment]
https://github.com/JensPauwels/nvim/tree/cmp-upgrade This is a link to my nvim setup.

**Comment by hrsh7th** [comment]
I don't know what happens if we use both of the lspconfig and lsp-installer.

In the first place, I say that even if I made the minimum configuration, it did not reproduce. Make the minimum configuration to reproduce.

**Comment by dmitmel** [comment]
@JensPauwels @nikbrunner I am guessing here, but it looks like you have an old version of Nodejs installed, which doesn't support the `objecr?.key` syntax.

**Comment by nikbrunner** [comment]
> @JensPauwels @nikbrunner I am guessing here, but it looks like you have an old version of Nodejs installed, which doesn't support the `object?.key` syntax.

- So for work I have to use `node 12.13.0` and I now switched for testing to just the latest version with `nvm use node` which got me to `17.2.0`
- When I entered a project with `nvim` and navigated to a `.css` file, I got this error
  - `Spawning language server with cmd: "vscode-css-language-server" failed. The language server is either not installed, missing from PATH, or not executable`
- I tried to re-install the `cssls` language server with `lsp-installer`, but to no success
- I ran manually `npm i -g vscode-langservers-extracted` and re-entered the file
- Now it worked (See Screenshot)
- When I switch back to `node 12.13.0` and I re-enter, I get the error `Client 1 quit with exit code 1 and signal 0`, which is also reflected in the log file

## `:CmpStatus` with `node 17.2.0` and manually installed language server
<img width="913" alt="image" src="https://user-images.githubusercontent.com/46924729/147477641-66c1165b-8caf-47a6-89c8-fff5a42de53f.png">

## `~/.cache/nvim/lsp.log` when entering file with `node 12.13.0`
```
[START][2021-12-27 14:24:56] LSP logging initiated
[START][2021-12-27 14:29:34] LSP logging initiated
[ERROR][2021-12-27 14:29:40] .../vim/lsp/rpc.lua:417	"rpc"	"vscode-css-language-server"	"stderr"	"/Users/nibru/.nvm/versions/node/v12.13.0/lib/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/linkedMap.js:40\n        return this._head?.value;\n                          ^\n\nSyntaxError: Unexpected token '.'\n    at Module._compile (internal/modules/cjs/loader.js:892:18)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)\n    at Module.load (internal/modules/cjs/loader.js:812:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:724:14)\n    at Module.require (internal/modules/cjs/loader.js:849:19)\n    at require (internal/modules/cjs/helpers.js:74:18)\n    at Object.<anonymous> (/Users/nibru/.nvm/versions/node/v12.13.0/lib/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/api.js:37:21)\n    at Module._compile (internal/modules/cjs/loader.js:956:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)\n    at Module.load (internal/modules/cjs/loader.js:812:32)\n"
[START][2021-12-27 14:30:26] LSP logging initiated
[START][2021-12-27 14:31:22] LSP logging initiated
[START][2021-12-27 14:32:47] LSP logging initiated
[ERROR][2021-12-27 14:32:56] .../vim/lsp/rpc.lua:417	"rpc"	"vscode-css-language-server"	"stderr"	"/Users/nibru/.nvm/versions/node/v12.13.0/lib/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/linkedMap.js:40\n        return this._head?.value;\n                          ^\n\nSyntaxError: Unexpected token '.'\n    at Module._compile (internal/modules/cjs/loader.js:892:18)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)\n    at Module.load (internal/modules/cjs/loader.js:812:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:724:14)\n    at Module.require (internal/modules/cjs/loader.js:849:19)\n    at require (internal/modules/cjs/helpers.js:74:18)\n    at Object.<anonymous> (/Users/nibru/.nvm/versions/node/v12.13.0/lib/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/api.js:37:21)\n    at Module._compile (internal/modules/cjs/loader.js:956:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)\n    at Module.load (internal/modules/cjs/loader.js:812:32)\n"
```

## Conclusion
The `node` version is definitely a problem, but I wonder if this prevents me from using `neovim` for my work related projects where I have to use an older `node` version

**Comment by hrsh7th** [comment]
I'll try.

**Comment by JensPauwels** [comment]
I do indeed use node 12 for compatibility with older projects.

**Comment by dmitmel** [comment]
@hrsh7th Try lowering the target when building components of VSCode in vscode-langservers-extracted. I think, for their internal language servers it is defined in <https://github.com/microsoft/vscode/blob/main/extensions/tsconfig.base.json>.

**Comment by hrsh7th** [comment]
I'm trying to transpile all modules via babel (/preset-env).

**Comment by hrsh7th** [comment]
@JensPauwels I've published the v4.0.0.

**Comment by IbnDaanis** [comment]
I'm getting this issue sadly. Does anyone know a proper fix?

**Comment by IrwinJuice** [comment]
Hi, I'm sorry for opening it again. 

I want to add some notes for Ubuntu users.

Today I had a similar problem. But in my case, CSS and HTML completion doesn't work because of the  'snap' package Neovim on Ubuntu. 

```:cheсkhealth``` showed something like this:

> Failed to load parser: uv_dlopen: /snap/core18/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (requ
ired by /lib/x86_64-linux-gnu/libstdc++.so.6)

So I deleted 'snap' version, and install Neovim from github (because apt contain only neovim 0.4.0)

https://github.com/neovim/neovim/releases/nightly

> Debian Package
> 
> Download ```nvim-linux64.deb```
> Install the package using ```sudo apt install ./nvim-linux64.deb```
> Run nvim

After that CSS and HTML completion works perfectly.

**Comment by Leo-Zarni01** [comment]
May I ask how this issue was resolved? I'm currently experiencing a similar issue that's why. I am also using the latest node version as well.
