### ISSUE TITLE
Question: How to navigate between TypeScript overloads

### ISSUE THREAD

**Issue by mblarsen** [hrsh7th/cmp-nvim-lsp#15]
TypeScript and other languages support function overloading. Here is a screenshot showing `pipe()`

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/247048/140054405-04364d34-de29-42ba-9ea4-7a016a551add.png">

As you can see this function has +10 overloads.

Is it possible to flip through these versions of `pipe()`

**Comment by hrsh7th** [comment]
It's nvim built-in lsp's feature.

**Comment by mblarsen** [comment]
Okay, would you know where to read about it? What is the feature called?

**Comment by hrsh7th** [comment]
It's `textDocument/hover`, I guess.
