### ISSUE TITLE
[Avoid Extra '>'] There will be extra '>' when complete include file

### ISSUE THREAD

**Issue by hiberabyss** [hrsh7th/cmp-nvim-lsp#18]
There will be extra '>' when complete include file:

![image](https://user-images.githubusercontent.com/2898670/143549001-151b6540-9bcd-4a8f-b448-2d15ee88a77f.png)

**Comment by hrsh7th** [comment]
I don't think it is a problem. It's just personal preference. If you still think it's problem, you should open issue for clangd.

**Comment by igorlfs** [comment]
@hrsh7th hey can you take a look at this issue again? I've opened a bug report on clangd but according to them, it's a client side bug.
