### ISSUE TITLE
cmp_nvim_lsp module not found

### ISSUE THREAD

**Issue by JustSage** [hrsh7th/cmp-nvim-lsp#25]
```lua
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities = require('cmp_nvim_lsp').update_capabilities(capabilities)
```

Can't find cmp_nvim_lsp module, error coming from the require method. 

I have cmp installed with all relevant extensions, yet it yields the same result wherever I try to place these lines (lspconfig.lua file or in seperate lsp configuration files).

**Comment by Shougo** [comment]
You should upload the minimal vimrc

**Comment by mkubasz** [comment]
I have this same issue.

**Comment by ricjorge** [comment]
Not sure if the same issue, but when running CmpStatus on nvim, I get the following output:

# unknown source names
- nvim_lsp

**Comment by Shougo** [comment]
Please upload the minimal vimrc

**Comment by ricjorge** [comment]
Nevermind. Just found out that I have to launch RustStartStandaloneServerForBuffer manually on nvim for whatever reason :) Thanks for your answer anyway.

**Comment by Shougo** [comment]
OK.  I think the issue should be closed.

**Comment by mgrubb** [comment]
I'm having the same issue.  Here is a minimal init.lua:
```lua
require('packer').startup(function()
  -- Base functionality
  use 'wbthomason/packer.nvim' 

  -- Autocomplete
  use 'hrsh7th/nvim-cmp'
  use { 'hrsh7th/cmp-nvim-lsp', after = 'nvim-cmp' }
  use { 'hrsh7th/cmp-buffer', after = 'nvim-cmp' }
  use { 'hrsh7th/cmp-path', after = 'nvim-cmp' }
  use { 'hrsh7th/cmp-cmdline', after = 'nvim-cmp' }
end)

local lsp_servers = {'gopls'}
-- Setup Autocomplete capabilities
local capabilities = require('cmp_nvim_lsp')
  .update_capabilities(vim.lsp.protocol.make_client_capabilities())

for _, lsp in pairs(lsp_servers) do
  require('lspconfig')[lsp].setup {
    capabilities = capabilities,
  }
end
```

**Comment by mgrubb** [comment]
Ok, so this turns out to be a problem with my packer config.
For some reason, packer was marking all the plugins with the `after` key as optional, and not loading them.
If I remove the `after` or put those dependencies in the requires field of nvim-cmp then all works as expected.
Sorry for the noise, hope this helps someone else.

**Comment by Shougo** [comment]
@hrsh7th I think it can be closed.

**Comment by hrsh7th** [comment]
Yes. If you want to use `require('cmp_nvim_lsp') in your vimrc, You can't use lazy-loading.
