### ISSUE TITLE
nvim-cmp selection jumps to options with this source enabled (only with rust-analyzer?)

### ISSUE THREAD

**Issue by poperigby** [hrsh7th/cmp-nvim-lsp#29]
# Current Behavior
When the `nvim_lsp` nvim-cmp source is enabled, the selection in the nvim-cmp menu will jump to options supplied by rust-analyzer server. If this source isn't enabled, nothing is selected until trigger `cmp.select_next_item()`. 

# Expected behavior
Nothing is selected in the nvim-cmp menu until I trigger `cmp.select_next_item()` or `cmp.select_prev_item()`.

# Steps to reproduce
1. Enable `nvim_lsp` source:
```lua
cmp.setup({
    sources = {
        { name = "nvim_lsp" },
    },
})
```
2. Install rust-anaylzer and set up Neovim to use it
3. Open a Rust file
4. Start typing

# Additional information
I'm not having this problem with other language servers. I've tested sumneko_lua and pyright. This what I have for setting up my LSP servers, and I install them with nvim-lsp-installer:
```lua
lsp_installer.setup({})

lspconfig.util.default_config = vim.tbl_extend("force", lspconfig.util.default_config, {
    on_attach = on_attach,
})

for _, server in ipairs(lsp_installer.get_installed_servers()) do
    lspconfig[server.name].setup({})
end
```

I've managed to reproduce this with a very minimal nvim-cmp configuration:
```lua
local cmp = require("cmp")
cmp.setup({
    sources = {
        { name = "nvim_lsp" },
})
```

# Videos

With `nvim_lsp` source:

https://user-images.githubusercontent.com/20866468/179830268-615138e8-9f5b-44a3-88d3-5470f10bc854.mp4

Without `nvim_lsp` source:

https://user-images.githubusercontent.com/20866468/179830472-8ab139d7-3ac5-400d-89ee-ed3ebcbbd971.mp4

**Comment by hpanchal092** [comment]
This is actually a feature provided by LSPs such as rust-analyzer and gopls. It's called preselect, and you can disable it by adding `preselect = cmp.PreselectMode.None` to your `cmp.setup` function.

**Comment by poperigby** [comment]
Thank you!
