### ISSUE TITLE
Filter some suggestions provided by cmp-nvim-lsp

### ISSUE THREAD

**Issue by carlesba** [hrsh7th/cmp-nvim-lsp#47]
I get this suggestions in my `tsx` files which basically transforms any word into an XML tag. 
I can't find a way to remove this specific option without removing all the LSP suggestions.

<img width="405" alt="Screenshot 2022-11-27 at 20 36 48" src="https://user-images.githubusercontent.com/1178459/204156010-70cd3215-c4d9-4b4d-a290-deaa7b84934e.png">

**Comment by nikitarevenco** [comment]
I also have this exact issue, can you please tell me how you fixed this?
