### ISSUE TITLE
Hide warning and error show on editor

### ISSUE THREAD

**Issue by TroyCode3** [hrsh7th/cmp-nvim-lsp#49]
The diagnostic shows like this:
![image](https://user-images.githubusercontent.com/88051085/211112187-edc0f705-00a3-4ee2-97da-7a7e4a4ddf96.png)
How do I hide the 'E' and 'W' on the left side, and the diagnostic on the right side?

**Comment by gegoune** [comment]
That has nothing to do with this source and cmp plugin in general. You need to set that in configuration for lsp client (I assume it's built in lsp client). You most likely have signs defined for those diagnostics, have a look at help for lsp in nvim.

**Comment by rorystephenson** [comment]
This worked for me:
```lua
-- Make diagnostics less intrusive
vim.lsp.handlers["textDocument/publishDiagnostics"] = vim.lsp.with(
  vim.lsp.diagnostic.on_publish_diagnostics, {
    virtual_text = false,
    signs = false,
    underline = true,
    severity_sort = true,
  }
)
```

**Comment by TroyCode3** [comment]
Thank you @rorystephenson!
