### ISSUE TITLE
Lazy loading II

### ISSUE THREAD

**Issue by akinsho** [hrsh7th/cmp-nvim-lsp#5]
Hey @hrsh7th,

sorry to continue on this thread https://github.com/hrsh7th/nvim-cmp/issues/65#issuecomment-906181963 I know you're not a huge fan, but I was looking through the code base and it looks like if you defer requiring `cmp` till it's needed in the `insert_enter` function then actually this plugins dependency on cmp will be delayed.

So rather than requiring `cmp` here
https://github.com/hrsh7th/cmp-nvim-lsp/blob/c0b38c140ebcb631a08339ea1263789b53a0b84d/lua/cmp_nvim_lsp/init.lua#L1

You can move the require to 
https://github.com/hrsh7th/cmp-nvim-lsp/blob/c0b38c140ebcb631a08339ea1263789b53a0b84d/lua/cmp_nvim_lsp/init.lua#L48

and this will defer the require till insert enter which will allow lazy loading to work.

Tbh is seems to be good practice to delay deferring requires till the point where they are needed so that just requiring a module doesn't immediately trigger a bunch of requires anyway

**Comment by ignamartinoli** [comment]
I found a warning.

If I remove the compilation result from `packer.nvim` with

```
rm $XDG_CONFIG_HOME/nvim/plugin/packer_compiled.lua
```

and then enter **Neovim** and run `:PackerCompile` to have a fresh state, upon entering _Insert_ mode I receive the error

```
Error detected while processing InsertEnter Autocommands for "*":
E5108: Error executing lua ...pack/packer/start/cmp-nvim-lsp/lua/cmp_nvim_lsp/init.lua:48: module 'cmp' not found:
        no field package.preload['cmp']
        no file './cmp.lua'
        no file '/usr/share/luajit-2.1.0-beta3/cmp.lua'
        no file '/usr/local/share/lua/5.1/cmp.lua'
        no file '/usr/local/share/lua/5.1/cmp/init.lua'
        no file '/usr/share/lua/5.1/cmp.lua'
        no file '/usr/share/lua/5.1/cmp/init.lua'
        no file '/home/sicro/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/cmp.lua'
        no file '/home/sicro/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/cmp/init.lua'
        no file '/home/sicro/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/cmp.lua'
        no file '/home/sicro/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/cmp/init.lua'
        no file './cmp.so'
        no file '/usr/local/lib/lua/5.1/cmp.so'
        no file '/usr/lib64/lua/5.1/cmp.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/home/sicro/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/cmp.so'
stack traceback:
        [C]: in function 'require'
        ...pack/packer/start/cmp-nvim-lsp/lua/cmp_nvim_lsp/init.lua:48: in function '_on_insert_enter'
        [string ":lua"]:1: in main chunk
```

I load `cmp` with

```lua
use {
	'hrsh7th/nvim-cmp',
	after = { 'nvim-autopairs', 'LuaSnip', 'lspkind-nvim' },
	config = function ()
		...
	end,
	requires = {
		{
			'hrsh7th/cmp-path',
			after = 'nvim-cmp'
		},
		{
			'onsails/lspkind-nvim',
			event = 'InsertEnter'
		},
		{
			'saadparwaiz1/cmp_luasnip',
			after = 'nvim-cmp'
		},
		{
			'L3MON4D3/LuaSnip',
			event = 'InsertEnter'
		}
	}
}
```

and I think what is triggering this is this line in my `nvim-lspconfig` configuration

```lua
capabilities = require 'cmp_nvim_lsp'.update_capabilities(
	vim.lsp.protocol.make_client_capabilities()
)
```

**Comment by NathanCummings** [comment]
> 

I also experience this issue. Is it a mistaken my end?
