### ISSUE TITLE
Won't send more requests if **one** character no completions.

### ISSUE THREAD

**Issue by scottming** [hrsh7th/cmp-nvim-lsp#55]
Some LSPs do not autocomplete when typing a **single** character because it would generate too much noise. They only autocomplete when there are **two** characters, which causes issues for cmp. When cmp detects an empty table for autocompletion of a character, it does not send more requests after the document has been changed.

For example:

When I type `S`, LSP has no completions, so I continue typing `t`, normally cmp should send a new request, but it won't, so no completions too.

**Comment by Shougo** [comment]
Can you upload the example LSP?

**Comment by hrsh7th** [comment]
If that's true, I think it could be a bug in the LSP server.
Which language server are you having problems with?

**Comment by scottming** [comment]
> If that's true, I think it could be a bug in the LSP server.
> Which language server are you having problems with?

I'm using Lexical, I'm the committer too. We intentionally don't allow one character completion: https://github.com/lexical-lsp/lexical/blob/main/apps/server/lib/lexical/server/code_intelligence/completion.ex#L69

I don't think it's a server-side bug because VScode and Emacs work fine.

**Comment by scottming** [comment]
This is the code, when I type `S`(send completion request), and `t`(only send `didChange` request)

<img width="269" alt="image" src="https://user-images.githubusercontent.com/12830256/234249291-621d40da-94f6-4a42-be08-3219de2d0ce8.png">

and this is the log

```log
[DEBUG][2023-04-25 18:23:40] .../vim/lsp/rpc.lua:284	"rpc.send"	{
  id = 2,
  jsonrpc = "2.0",
  method = "textDocument/completion",
  params = {
    context = {
      triggerKind = 1
    },
    position = {
      character = 5,
      line = 3
    },
    textDocument = {
      uri = "file:///Users/scottming/Code/dummy/lib/dummy.ex"
    }
  }
}
[DEBUG][2023-04-25 18:23:40] .../vim/lsp/rpc.lua:387	"rpc.receive"	{
  id = 2,
  jsonrpc = "2.0",
  result = {}
}
[DEBUG][2023-04-25 18:23:40] .../vim/lsp/rpc.lua:387	"rpc.receive"	{
  jsonrpc = "2.0",
  method = "textDocument/publishDiagnostics",
  params = {
    diagnostics = {},
    uri = "file:///Users/scottming/Code/dummy/lib/dummy.ex"
  }
}
[DEBUG][2023-04-25 18:23:41] .../vim/lsp/rpc.lua:284	"rpc.send"	{
  jsonrpc = "2.0",
  method = "textDocument/didChange",
  params = {
    contentChanges = { {
        range = {
          ["end"] = {
            character = 5,
            line = 3
          },
          start = {
            character = 5,
            line = 3
          }
        },
        rangeLength = 0,
        text = "t"
      } },
    textDocument = {
      uri = "file:///Users/scottming/Code/dummy/lib/dummy.ex",
      version = 12
    }
  }
}
[DEBUG][2023-04-25 18:23:41] .../vim/lsp/rpc.lua:387	"rpc.receive"	{
  jsonrpc = "2.0",
  method = "textDocument/publishDiagnostics",
  params = {
    diagnostics = {},
    uri = "file:///Users/scottming/Code/dummy/lib/dummy.ex"
  }
}
```

**Comment by hrsh7th** [comment]
Thank you detailed response.

Hmm. . . Let's track how VSCode handles null return values for textDocument/completion.

Also, I think the server should return isIncomplete=true instead of just returning null. What are your thoughts on this?

**Comment by scottming** [comment]
@hrsh7th thanks for your reminder, after I change the result of the single-character response, it works. I'll send a PR for lexical.
