### ISSUE TITLE
How to install cmp-nvim-lsp 

### ISSUE THREAD

**Issue by CatKoder123** [hrsh7th/cmp-nvim-lsp#59]
hey, i seem to cant be installing cmp_nvim_lsp
here is the error 
`Error detected while processing InsertEnter Autocommands for "*":
Error executing lua callback: ...pack\packer\start\cmp-nvim-lsp/lua/cmp_nvim_lsp/init.lua:96: module 'cmp' not found:
        no field package.preload['cmp']
        no file '.\cmp.lua'
        no file 'C:\ProgramData\Scoop\apps\neovim\current\bin\lua\cmp.lua'
        no file 'C:\ProgramData\Scoop\apps\neovim\current\bin\lua\cmp\init.lua'
        no file '.\cmp.dll'
        no file 'C:\ProgramData\Scoop\apps\neovim\current\bin\cmp.dll'
        no file 'C:\ProgramData\Scoop\apps\neovim\current\bin\loadall.dll'
stack traceback:
        [C]: in function 'require'
        ...pack\packer\start\cmp-nvim-lsp/lua/cmp_nvim_lsp/init.lua:96: in function <...pack\packer\start\cmp-nvim-lsp/lua/cmp_nvim_lsp/init.lua:95>`

If You Need my config files like init.lua and stuff comment here

**Comment by capitanics** [comment]
Try installing it like this: 
```lua
  use {
	  {'hrsh7th/nvim-cmp'},     -- Required
	  {'hrsh7th/cmp-nvim-lsp'}, -- Required
	  {'L3MON4D3/LuaSnip'},     -- Required
  }
```

**Comment by CatKoder123** [comment]
> Try installing it like this:
> 
> ```lua
>   use {
> 	  {'hrsh7th/nvim-cmp'},     -- Required
> 	  {'hrsh7th/cmp-nvim-lsp'}, -- Required
>   }
> ```

It Workd ;)
