### ISSUE TITLE
textEdit completion item property is not resolved lazily

### ISSUE THREAD

**Issue by ypomortsev** [hrsh7th/cmp-nvim-lsp#72]
rust-analyzer 2024-10-07 and newer does not send the `textEdit` completion property by if the client can resolve it lazily, introduced in rust-lang/rust-analyzer#18167.

cmp-nvim-lsp includes `textEdit` in its [`default_capabilities`](https://github.com/hrsh7th/cmp-nvim-lsp/blob/main/lua/cmp_nvim_lsp/init.lua#L63) but does not seem to resolve it lazily, breaking completion:

Observed with `textEdit` in capabilities:

![Screenshot from 2024-10-14 13-20-39](https://github.com/user-attachments/assets/5d5fdf97-c3d3-4bf2-9d42-ce0751db06cf)
(pressing Enter to complete)
![Screenshot from 2024-10-14 13-21-16](https://github.com/user-attachments/assets/14ad01f3-f76b-4a7c-9cc5-00fb85b50af2)

Expected, without `textEdit` in capabilities:

![Screenshot from 2024-10-14 13-21-59](https://github.com/user-attachments/assets/b4633bda-ff3b-436b-838f-6ee12a51b7d2)
(pressing Enter to complete)
![Screenshot from 2024-10-14 13-22-22](https://github.com/user-attachments/assets/bf335337-3567-432d-8f50-38932f42788e)

**Comment by kalvinpearce** [comment]
Same issue on my end. A workaround for now is to use the [2024-09-30 release](https://github.com/rust-lang/rust-analyzer/releases/tag/2024-09-30) of rust-analyzer.
For those using mason to handle language servers, you can uninstall the current version of rust-analyzer and then run `:MasonInstall rust-analyzer@2024-09-30`

**Comment by ouuan** [comment]
Another workaround is to not override the default `capabilities` with `require 'cmp_nvim_lsp'.default_capabilities()` for `rust_analyzer`. Not sure about the downsides, though.

**Comment by coder3101** [comment]
Actually `default_capabilities()` take an override table which can be used to [override some capabilities](https://github.com/coder3101/dotfiles/blob/125f2de50f80f3757d5ff1563096aaa5ac8d15f4/nvim/.config/nvim/lua/plugins/lsp.lua#L94-L111). In our case, resolve support properties can be overridden as

```lua
require("cmp_nvim_lsp").default_capabilities(
    {
        resolveSupport = {
            properties = {
                "documentation",
                "detail",
                "additionalTextEdits",
                "sortText",
                "filterText",
                "insertText",
                "insertTextFormat",
                "insertTextMode"
            }
        }
    }
)
```
imo this is better than not having to override the complete cmp default capabilities.

**Comment by VVishion** [comment]
Doing

```lua
require("cmp_nvim_lsp").default_capabilities(
    {
        resolveSupport = {
            properties = {
                "documentation",
                "detail",
                "additionalTextEdits",
                "sortText",
                "filterText",
                "insertText",
                "insertTextFormat",
                "insertTextMode"
            }
        }
    }
)
...
```
with the newest version didnt work for me

**Comment by ypomortsev** [comment]
Repro with minimal config:

### `init.lua`

```
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

require("lazy").setup({
  {
    'williamboman/mason.nvim',
    dependencies = {
      { 'neovim/nvim-lspconfig' },
      { 'williamboman/mason-lspconfig.nvim' },
    }
  },
  {
    'hrsh7th/nvim-cmp',
    dependencies = {
      { 'hrsh7th/cmp-buffer' },
      { 'hrsh7th/cmp-nvim-lsp' },
    },
    config = function()
      local cmp = require('cmp')
      cmp.setup({
        sources = cmp.config.sources({
          { name = 'nvim_lsp' },
        }),
        snippet = {
          expand = function(args)
            vim.snippet.expand(args.body)
          end,
        },
        mapping = cmp.mapping.preset.insert({
          ['<C-Space>'] = cmp.mapping.complete(),
          ['<C-e>'] = cmp.mapping.abort(),
          ['<CR>'] = cmp.mapping.confirm({ select = true }),
        }),
      })
    end
  }
})

require('mason').setup()

local mason_lspconfig = require('mason-lspconfig')
mason_lspconfig.setup({
  ensure_installed = { 'rust_analyzer@nightly' },
  automatic_installation = true,
})

local lsp_capabilities = require('cmp_nvim_lsp').default_capabilities(
  {
    resolveSupport = {
      properties = {
        "documentation",
        "detail",
        "additionalTextEdits",
        "sortText",
        "filterText",
        "insertText",
        -- Remove `textEdit` to fix https://github.com/hrsh7th/cmp-nvim-lsp/issues/72
        "textEdit",
        "insertTextFormat",
        "insertTextMode",
      }
    }
  }
)

local lspconfig = require('lspconfig')

lspconfig.rust_analyzer.setup({
  capabilities = lsp_capabilities,
})
```

### `Cargo.toml`

```
[package]
name = "cmp-nvim-lsp-72"
version = "0.1.0"
edition = "2021"
```

1. `mkdir cmp-nvim-lsp-72 && cd cmp-nvim-lsp-72 && mkdir src && touch src/main.rs`
2. Create `init.lua`
3. Create `Cargo.toml`
4. `vim -u init.lua src/main.rs`
5. Type:
   `fn main() {`
    <kbd>Enter</kbd>
   `print`
   <kbd>Ctrl-N</kbd> (should select `println!(…)`)
   <kbd>Enter</kbd> (completes `println!(…)` but should complete `println!(|)` with cursor between parens)

**Comment by tan-wei** [comment]
Hmm, met the same issue now with the latest version (and I can confirm it is the recently commit will cause this problem).

**Comment by marcelarie** [comment]
> Doing
> with the newest ra version didnt work for me

@VVishion for me what fixed it with the `rustaceanvim` config is to use `vim.lsp.protocol.make_client_capabilities` directly.

```lua
vim.g.rustaceanvim = {
   server = {
     capabilities = vim.lsp.protocol.make_client_capabilities(),
```

**Comment by tan-wei** [comment]
@marcelarie It works, thanks.

**Comment by sineptic** [comment]
For me it works the same as 
``` lua
capabilities = {
    textDocument = {
        completion = {
            completionItem = {
                snippetSupport = false,
            },
        },
    },
},
```

Now some snippets doesn't work. For example:
`"asfd".dbg` -> `dbg!("asdf")`
or 
`"asfd".ok` -> `Ok("asdf")`

**Comment by sineptic** [comment]
Also issue doesn't occur if this is first item.
https://github.com/user-attachments/assets/69bc4ed6-88d4-413c-bf54-cc3609a135ef

**Comment by ttytm** [comment]
IMHO a very high severity issue. It frequently breaks workflows and often results in unusable completions.

**Comment by ogios** [comment]
I think [this](https://github.com/rust-lang/rust-analyzer/pull/18503#issuecomment-2483261348) might be a better solution(temporarily) as to `snippetSupport` is indeed useful in most circumstances (for me).

```lua
  {
    "hrsh7th/nvim-cmp",
    opts = function(_, opts)
      local cmp = require("cmp")
      opts.mapping = vim.tbl_extend("force", opts.mapping, {
        ["<Tab>"] = cmp.mapping.select_next_item({ behavior = cmp.SelectBehavior.Select }), -- This used to be `cmp.SelectBehavior.Insert`
        ["<S-Tab>"] = cmp.mapping.select_prev_item({ behavior = cmp.SelectBehavior.Select }),
      })
    end,
  },
```
